#!/usr/bin/env python3
from pathlib import Path
import json
import logging
import os
import sys

current_dir = Path.cwd()

mcserver_path = current_dir / ".mcserver"
configs_path = mcserver_path / "configs"

default_configs = {
  "server": {
    "jarfile": "Launcher.jar",
    "ram": {
      "min": 512,
      "max": 2_048
    },
    "hide_gui": True
  }
}

# Setup logger
logger = logging.getLogger("mcserver")

# Check directory functions
def ensure_mcserver_dir():
  if not mcserver_path.exists():
    raise FileNotFoundError("Not a MCServer-managed directory")

# Configuration fuctions
def generate_config(config_name):
  config_filename = f"{config_name}.json"
  config_path = configs_dir / config_filename
  relative_config_path = os.path.relpath(config_path, current_dir)

  try:
    with open(config_path, mode="xt") as config_file:
      json.dump(
        default_configs[config_name],
        config_file,
        indent=2
      )
  except Exception as error:
    raise Exception(f"Failed to create configuration file for {config_name}: {error}")

def load_config(config_name):
  config_filename = f"{config_name}.json"
  config_path = configs_dir / config_filename
  relative_config_path = os.path.relpath(config_path, current_dir)

  try:
    with open(config_path, mode="rt") as config_file:
      return [json.load(config_file), relative_config_path]
  except Exception as error:
    raise Exception(f"Failed to load configuration for {config_name}: {error}")

# Command functions
def initialize_directory():
  pathlib.Path.mkdir(mcserver_path, exist_ok=True)

  pathlib.Path.mkdir(configs_dir, exist_ok=True)
  generate_config("server")

  logger.info("Directory has been initialized")

def start_server():
  ensure_mcserver_dir()

  loaded_config = load_config("server")

  server_config = loaded_config[0]
  if not Path(server_config["jarfile"]).exists():
    raise FileNotFoundError(f"Can't find '{server_config['jarfile'}'")

  memory_limit = server_config["ram"]

  if memory_limit["min"] > memory_limit["max"]:
    logger.error(f"Minimum RAM cannot exceed the maximum RAM");
    logger.info(f"Related file: {loaded_config[1]}")

  command_args = [
    "java",
    f"-Xms{memory_limit['min']}M",
    f"-Xmx{memory_limit['max']}M",
    "-jar",
    server_config["jarfile"]
  ]

  if server_config["hide_gui"]:
    command_args.append("nogui")

  logger.debug(f"Running command: {' '.join(command_args)}")
  os.execvp("java", command_args)

def main():
  logging.basicConfig(
    level=logging.INFO,
    format="[%(levelname)s]: %(message)s",
    stream=sys.stdout
  )

  cli_args = sys.argv[1:] if len(sys.argv) > 1 else [""]
  command = cli_args[0]

  try:
    match command:
      case "init":
        initialize_directory()
      case "start":
        start_server()
      case "":
        raise Exception("No command was provided")
      case _:
        raise Exception(f"Unknown command: {command}")
  except Exception as error:
    logger.error(error)
    sys.exit(1)

if __name__ == "__main__": main()
