#!/usr/bin/env python3
import os
import sys

def start_server():
  java_command_argv = [
    "java",
    "-Xms512M",
    "-Xmx2G",
    "Launcher.jar",
    "nogui"
  ]

  os.execvp("java", java_command_argv)

def main():
  script_args = sys.argv[1:] if len(sys.argv) > 1 else [""]

  command = script_args[0]
  match command:
    case "start":
      start_server()
    case "":
      print("[ERROR]: No command was provided")
    case _:
      print(f"[ERROR]: Unknown command: {command}")

if __name__ == "__main__": main()