#!/usr/bin/env python3
import logging as log
import os
import requests
import sys

# RAM size in MebiByte
configs = {
  "server": {
    "jarfile": "Launcher.jar",
    "ram": {
      "min": 512,
      "max": 2_048
    },
    "hide_gui": True,
    "mc_version": "1.20.2",
    "software": {
      "loader": "fabric",
      "version": "0.18.4"
    }
  }
}

def search_mod(query):
  server_config = configs["server"]
  server_software = server_config["software"]

  search_filters = f"[\
[\"project_type:mod\"],\
[\"server_side:optional\"],\
[\"categories:{server_software['loader']}\"],\
[\"versions:{server_config['mc_version']}\"]\
]"

  response = requests.get(
    "https://api.modrinth.com/v2/search",
    params={
      "query": query,
      "facets": search_filters,
      "limit": 1
    },

    headers={
      "User-Agent": "Othecat35/MCServer/0.1"
    }
  )

  log.debug(f"Modrinth response:\n{response.text}")

def start_server():
  server_config = configs["server"]
  memory_limit = server_config["ram"]

  java_command_argv = [
    "java",
    f"-Xms{memory_limit['min']}M",
    f"-Xmx{memory_limit['max']}M",
    server_config["jarfile"]
  ]

  if server_config["hide_gui"]:
    java_command_argv.append("nogui")

  log.info("Starting Minecraft server...")
  log.debug(f"Executing command: {" ".join(java_command_argv)}")
  os.execvp("java", java_command_argv)

# Main
def main():
  log.basicConfig(
    format="[%(levelname)s]: %(message)s",
    level=log.DEBUG
  )

  script_args = sys.argv[1:] if len(sys.argv) > 1 else [""]
  command = script_args[0]

  match command:
    case "search":
      search_mod(" ".join(script_args[1:]))
    case "start":
      start_server()
    case "":
      log.error("No command was provided")
    case _:
      log.error(f"Unknown command: {command}")

if __name__ == "__main__": main()